Fixed UI components inside the ProfileScreen and added the feature to modify the profile picture by click
WanderWise-Inc/app pull request #134
Opened 2024-04-29 13:24 UTC by YofiY

Worked mainly on `profileScreen.kt`.

- Modified some of the UI components to follow the app's general theme.
- Added a composable squeletton to add the WanderBadges
- Added the feature to open a popup menu when clicking on the profile picture in order to change it.
- Deleted the second setting button inside the `TopAppBar`

2024-04-29 14:04 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> -                  FloatingActionButton(onClick = { /*Go to Edit Profile Screen*/}) {
Removed the double Edit profile button

2024-04-29 14:10 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> +
maybe a more compact variable name would be nice

2024-04-29 14:13 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> +
lgtm

2024-04-29 14:15 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> +}
lgtm, good stuff

2024-04-29 14:16 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> +
Something like: isPPChangeDDOpen

2024-04-29 14:17 UTC, ThomasPFMuller requested changes
Overall nice changes, please run the ktfmt formatter as the PR fails the CI check for ktfmt. Otherwise approved changes, like what you've done with the place

2024-04-29 14:57 UTC, 276746 reviewed
Waiting for answer to comment else all good

2024-04-29 14:57 UTC, 276746 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
>      androidx.compose.material.Scaffold(
Why is it still material and not material3 ?

2024-04-29 14:57 UTC, 276746 commented
You need to run ktfmtFormat and repush the code for the CI

2024-04-29 20:58 UTC, engjellismaili reviewed
Overall good code and nice way of dividing tasks, well done! Can you maybe just add some comments for a better understanding ?

2024-04-29 20:58 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> +   DropdownMenu(expanded = expanded, onDismissRequest = onDismissRequest) {
Good way of doing the selection of photos. Dividing tasks into multiple composable is a good way. For the implementation of the onClick function, found a better way of doing and will change that.

2024-04-29 20:58 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> +
nice way of dividing tasks into multiple composable functions.

2024-04-29 20:58 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> +    Text(text = "369 WanderPoints", modifier = Modifier.padding(8.dp), fontWeight = FontWeight.Bold)
good additions of modification for the box.

2024-04-30 16:41 UTC, YofiY commented
Thank you all for the reviews, I had troubles with my ktformatter config. I have now fixed it.

2024-05-01 10:03 UTC, ThomasPFMuller commented on app/build.gradle.kts
> +
Enormous impact, good change ;)

2024-05-01 10:11 UTC, ThomasPFMuller requested changes
You just need to remove the PROFILE_SCREEN_TEST_TAG and add the revert the change of firebaseAuth to FirebaseAuth.getInstance() as it removes the ability to mock

2024-05-01 10:11 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> +
can remove this and use TestTags.PROFILE_SCREEN

2024-05-01 10:11 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> +  val currentUid = FirebaseAuth.getInstance().currentUser?.uid ?: DEFAULT_USER_UID
For mocking in tests, I encourage the use of firebaseAuth.currentUser?.uid? instead of change

2024-05-01 10:11 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> +              // List scrollable itineraries associated with the user.
nice comments

2024-05-01 10:11 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> +        profile = profile) {}
lgtm

2024-05-01 10:11 UTC, ThomasPFMuller commented on app/src/test/java/com/github/wanderwise_inc/app/ui/navigation/HomeNavigationTest.kt
> +
nice addition for mocking the imageRepository

2024-05-01 13:48 UTC, ThomasPFMuller approved these changes
lgtm

2024-05-01 13:56 UTC, merged