Updated navigation and changed a few details
WanderWise-Inc/app pull request #135
Opened 2024-04-29 17:58 UTC by ThomasPFMuller

Updated navigation to look like Figma, added new "create your itinerary screen". Also removed some abandoned files such as TopNavigationBar and unused navigation graphs. Finally, added default text to Liked and Profile screen when no Itineraries exist to be displayed.

![navigation_update_illustration2](https://github.com/WanderWise-Inc/app/assets/100191653/6e734ecb-0e1d-4e0c-ab31-d9a268558480) ![liked_screen_update](https://github.com/WanderWise-Inc/app/assets/100191653/36d196ad-06d6-4b00-9a92-d050de046bfe)

2024-04-29 19:56 UTC, 276746 commented
You need to run ktfmtFormat and push again for CI

2024-04-29 20:15 UTC, 276746 requested changes

2024-04-29 20:15 UTC, 276746 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/navigation/graph/RootNavGraph.kt
> +          HomeScreen(imageRepository, mapViewModel, profileViewModel, firebaseAuth = firebaseAuth)
This is very triggering, pls change ASAP the way firebaseAuth is passed

2024-04-29 20:15 UTC, 276746 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/LikedScreen.kt
> +                    // color = MaterialTheme.colorScheme.
What is the problem with this ?

2024-04-29 20:15 UTC, 276746 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> +                Box(
Since this Box is almost the same as the one in LikedScreen, this could be a Composable with the corresponding text as parameter to avoid code duplication.

2024-04-29 20:15 UTC, 276746 commented on app/src/test/java/com/github/wanderwise_inc/app/ui/navigation/HomeNavigationTest.kt
Why did you make change if it still commented ? Does it work ?

2024-04-29 20:17 UTC, 276746 reviewed
Waiting for insight, and formatting

2024-04-29 21:06 UTC, engjellismaili reviewed
Overall good code and good ideas. Maybe you can modularize it a bit to be more efficient and doing less duplication of code. Well done

2024-04-29 21:06 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/MainActivity.kt
good way of doing some injections

2024-04-29 21:06 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/ui/home/HomeScreen.kt
lgtm, easier to test with injections.

2024-04-29 21:06 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/LikedScreen.kt
lgtm well done

2024-04-29 21:06 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/OverviewScreen.kt
lgtm but instead of creating tag objects for each screen, wouldn't it be easier to create a separate class that will instantiate all of them ?

2024-04-29 21:06 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/ui/navigation/graph/RootNavGraph.kt
> +          HomeScreen(imageRepository, mapViewModel, profileViewModel, firebaseAuth = firebaseAuth)
i think that he needs to do it that way to inject firebase for testing

2024-04-29 21:06 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> +                Box(
Was going to say the same, well noticed.

2024-04-29 21:06 UTC, engjellismaili commented on app/src/test/java/com/github/wanderwise_inc/app/ui/navigation/HomeNavigationTest.kt
do you want to change your tests or is there a specific reason to comment them ?

2024-04-30 16:23 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/navigation/graph/RootNavGraph.kt
> +          HomeScreen(imageRepository, mapViewModel, profileViewModel, firebaseAuth = firebaseAuth)
exactly

2024-04-30 16:24 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/LikedScreen.kt
> +                    // color = MaterialTheme.colorScheme.
I don't really understand what your problem with this is, could you elaborate?

2024-04-30 16:25 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/OverviewScreen.kt
Good idea, I will try to do that

2024-04-30 16:49 UTC, ThomasPFMuller commented on app/src/test/java/com/github/wanderwise_inc/app/ui/navigation/HomeNavigationTest.kt
Yes I am in the process of making them work

2024-04-30 21:43 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> +                Box(
Done in ItineraryListScrollable

2024-04-30 21:43 UTC, ThomasPFMuller commented on app/src/test/java/com/github/wanderwise_inc/app/ui/navigation/HomeNavigationTest.kt
It works now (finally)

2024-05-01 08:25 UTC, 276746 approved these changes

2024-05-01 08:26 UTC, merged