Create/navigation
WanderWise-Inc/app pull request #191
Opened 2024-05-08 14:43 UTC by ThomasPFMuller

Added navigation for the itinerary creation steps as well as tests for new code. It is important to keep the testTags so that the tests still pass after changes.

![image](https://github.com/WanderWise-Inc/app/assets/100191653/e3dc69ac-0f9a-49c7-8d9f-1da05b1e8ef5) ![image](https://github.com/WanderWise-Inc/app/assets/100191653/6760f85a-303b-42d2-9b7d-c914b02e2931)

2024-05-08 16:05 UTC, ethangraham2001 approved these changes
Everything is looking good. Good job

2024-05-08 17:08 UTC, 276746 requested changes
There are some weird file in the PR. Waiting for an answer, but everything else seems good

2024-05-08 17:08 UTC, 276746 commented on app/src/test/java/com/github/wanderwise_inc/app/ui/navigation/CreationNavigationTest.kt
> +      every { mapViewModel.setItinerary(any()) } returns Unit
You can use `just Runs` instead of `returns Unit`

2024-05-08 17:08 UTC, 276746 commented on app/src/test/java/com/github/wanderwise_inc/app/ui/navigation/CreationNavigationTest.kt
> +class CreationPreviewNavigationTest {
Why is it not in its own file ?

2024-05-08 17:08 UTC, 276746 commented on hq
What is this ?

2024-05-08 17:08 UTC, 276746 commented on app/release/app-release.apk
Why is it present in the PR ?

2024-05-08 17:08 UTC, 276746 commented on app/release/baselineProfiles/0/app-release.dm
Same comment

2024-05-08 17:08 UTC, 276746 commented on app/release/baselineProfiles/1/app-release.dm
Same

2024-05-08 17:08 UTC, 276746 commented on app/release/output-metadata.json
S

2024-05-09 11:38 UTC, ThomasPFMuller commented on app/src/test/java/com/github/wanderwise_inc/app/ui/navigation/CreationNavigationTest.kt
> +class CreationPreviewNavigationTest {
This test class is related to the one corresponding to the file name, i did not think it was necessary to create a whole new file

2024-05-09 11:54 UTC, ThomasPFMuller commented on app/src/test/java/com/github/wanderwise_inc/app/ui/navigation/CreationNavigationTest.kt
> +      every { mapViewModel.setItinerary(any()) } returns Unit
I think returns Unit stops the execution of the method whereas just Runs executes the function. Here, since there is no use for the methods, I use returns Unit to stop the execution.

2024-05-09 12:02 UTC, ThomasPFMuller commented
Removed weird files and merged with new changes on main, awaiting re-review

2024-05-09 13:19 UTC, 276746 approved these changes
Fixed every things and answered my question. Good job !

2024-05-09 13:20 UTC, merged