finished title/description screen
WanderWise-Inc/app pull request #214
Opened 2024-05-12 14:40 UTC by gunnm0

Title/Description screen works, can write in it, functionality tested.

- title is limited to two lines
- fetches already set title and description if not set writes: ""
- writing to title and description update the Itinerary.Builder's title and description fields.
- the screen is scrollable so that we can write large description and scroll to see it

![Screenshot from 2024-05-12 16-35-08](https://github.com/WanderWise-Inc/app/assets/100207698/05e95ec4-ac89-4219-8130-65a767fe0877)

2024-05-12 20:21 UTC, ThomasPFMuller requested changes
Overall nice code, a few changes are needed, as the code would currently overuse firebase

2024-05-12 20:21 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescription.kt
> +              },
This looks good, but doesn't it use up resources uselessly by pushing the change to the viewmodel every time the title is changed? For the moment it doesn't pose any problems but when we'll use Firebase to store the backend, this will call a change in Firebase every time you type a new letter.

2024-05-12 20:21 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescription.kt
> +                createItineraryViewModel.getNewItinerary()?.description = description
Same comment

2024-05-12 20:21 UTC, ThomasPFMuller commented on app/src/test/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescriptionKtTest.kt
> +    }
Btw u are repeating these 6 lines every test, u can simplify it by creating a setup method with the @Before tag to make it run before each test

2024-05-12 20:21 UTC, ThomasPFMuller commented on app/src/test/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescriptionKtTest.kt
Nice tests :)

2024-05-13 09:28 UTC, engjellismaili reviewed
Lgtm, try to indicate your coverage in your PR description and try to reduce code complexity by separating functions. Overall good code, well done

2024-05-13 09:28 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescription.kt
Lgtm, one thing you should do is to separate the composable in pieces to reduce code complexity. For example, the LazyColumn could be in it's own Composable, and be called within the CreationStepChooseDescriptionScreen Composable

2024-05-13 09:28 UTC, engjellismaili commented on app/src/test/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescriptionKtTest.kt
Good tests, can you just maybe indicate your coverage so that we can tell if it's enough or not.

2024-05-13 11:11 UTC, 276746 approved these changes

2024-05-13 11:11 UTC, 276746 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescription.kt
> +                createItineraryViewModel.getNewItinerary()?.title = title
Why do we do this:
```
title = it 
createItineraryViewModel.getNewItinerary()?.title = title
```
and not 
```
createItineraryViewModel.getNewItinerary()?.title = it
```

I dont get it. Is it to update what is in the textfield too ?

2024-05-13 11:11 UTC, 276746 commented on app/src/test/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescriptionKtTest.kt
> +    assert(nullItineraryBuilder.description == description)
Maybe use the `assertEquals(<expected>, <actual>)`  from JUnit for this kind of assertion.

2024-05-13 11:45 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescription.kt
> +              },
Actually, you should create a new method in the itinerary builder to modify the title, which you then call through the viewmodel. This would only change the value in the itinerary builder and then apply the change when the itinerary is built and pushed to firebase

2024-05-13 12:01 UTC, gunnm0 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescription.kt
> +              },
The itinerary isn't pushed to firebase, I changed the code in order to use the builder methods.

2024-05-13 12:02 UTC, gunnm0 commented on app/src/test/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescriptionKtTest.kt
> +    }
One of the tests uses a different createItineraryViewModel.getNewItinerary() this is why I copied it for all but one.

2024-05-13 14:59 UTC, gunnm0 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescription.kt
> +                createItineraryViewModel.getNewItinerary()?.title = title
the text field is updated above, We could do this but it isn't a big deal

2024-05-13 14:59 UTC, gunnm0 commented on app/src/test/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescriptionKtTest.kt
I have 100% line coverage on new code.

2024-05-13 15:00 UTC, gunnm0 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescription.kt
If we struggle with code complexity I am willing to do the change however, I don't see the advantage of separating things like this

2024-05-13 15:02 UTC, gunnm0 commented on app/src/test/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescriptionKtTest.kt
> +    }
There is one test where I set the createItineraryViewModelTest.getNewItinerary() to another value, this is why I repeat it every time

2024-05-13 15:03 UTC, gunnm0 commented on app/src/test/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescriptionKtTest.kt
> +    assert(nullItineraryBuilder.description == description)
yes I could however it doesn't change anything

2024-05-13 15:33 UTC, ThomasPFMuller approved these changes

2024-05-13 15:33 UTC, gunnm0 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescription.kt
> +                createItineraryViewModel.getNewItinerary()?.title = title
"value" is the text that is written in the box and "createItineraryViewModel.getNewItinerary()?.title = title" is updating the title of the Itinerary.Builder. In this case, "title" gets set to "it" and then the newItinerary get set to title.

2024-05-13 15:34 UTC, gunnm0 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescription.kt
> +                createItineraryViewModel.getNewItinerary()?.title = title
I have changed the code so that it gets set with "it", makes it simpler to read.

2024-05-13 15:34 UTC, gunnm0 commented on app/src/test/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseDescriptionKtTest.kt
> +    assert(nullItineraryBuilder.description == description)
When merging with main I did the change

2024-05-13 15:46 UTC, merged