Added a feature that allows the user to see that he is following the chosen itinerary
WanderWise-Inc/app pull request #225
Opened 2024-05-14 17:54 UTC by imaneb942

- Small PR but the goal was to add a UI feature that allows the user to click on a button that goes from Follow to Following.
- It has been tested
- for now we don't have any itinerary that is "close" to the emulator's position
- goal for now for this feature is simply create an itinerary close to the emulator's COG to try it 
![image](https://github.com/WanderWise-Inc/app/assets/56965479/606fb570-b2e4-4f72-a222-0ea979154825)
![image](https://github.com/WanderWise-Inc/app/assets/56965479/ae005419-eb57-495a-9948-1e8db794de48)

2024-05-14 19:53 UTC, gunnm0 reviewed
other than a questionable UI there isn't anything of real value in this PR, I am sorry but with the deadline for MS3 approaching, I don't think it is a good idea to push this code into main since the "hard part" hasn't been implemented yet.

2024-05-14 19:53 UTC, gunnm0 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
> +        topBar = {
I am sorry but how do you want we to accept this... WHY DO YOU USE TOP BAR INSTEAD OF FLOATING ACTION BUTTON!!!!! I have already implemented something similar in CreationStepPreview. Please take a look at it and try to make it work, using the top bar is very ugly and lazy.

2024-05-14 20:01 UTC, gunnm0 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
> +        topBar = {
@imaneb942 je suis désolé mais on en a parlé aujourd'hui, je t'ai montré mon implementation et tu m'as dit que tu essayerai de faire marcher. Ca me gaz un peu qu'alors que j'ai essayé de t'aider tu décides  d'abandonner et de faire une PR

2024-05-15 09:04 UTC, imaneb942 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
> +        topBar = {
I use top bar in order to work best with the Scaffold structure that we have, I did take a lot at what you did and did inform you that I will try my best to change it, yet it was hard to do with the many errors that we had, what I also told you is that my goal was to implement a FEATURE not waste too much time on trying to make it "pretty" and that I would go back to the UI part a bit later when I finished my tasks that are more urgent for the epic. It seems to me that you are throwing a tantrum over a small detail and do not appreciate your tone. Saying I abandonned a feature is wrong, I did try to make it work for an important amount of time and it didn't work so I took the decision to move it to a more modularized way, now if you want to check it out by yourself you can but for now I am focusing on the other more heavy tasks that were assigned to me and do not appreciate someone questionning my ability to make a decision regarding the shape of a button.

2024-05-15 09:10 UTC, imaneb942 commented
@gunnm0 In order to answer your comment, I would suggest you to look at Mr. Candea's comments before writing, and also taking a lot at my description of the PR doesn't hurt also. You will find attached here a link to the message of the forum where Mr. Candea talked about how the size of a PR doesn't matter but rather what it brings to the app. As a developer I often take a look at the FIGMA of our team and noticed that the feature that I implemented in this PR did not exist previously, and I simply implemented that and PRed it in our main branch, what I do not appreciate is the fact that you solely judge a PR by its size when it shouldn't be the case, it should be about what it brings to the app, and what it brings is a feature that was in the figma that needed to be in our app. As answered previously, we can discuss colors and shapes if you want but let us not forget as you said that the MS3 is soon and we want useful features not unuseful ones ( gray or light gray?...) 
https://edstem.org/eu/courses/1193/discussion/109949

2024-05-15 09:17 UTC, ethangraham2001 requested changes

2024-05-15 09:18 UTC, gunnm0 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
> +        topBar = {
The real issue I have is not that the button is in my opinion ugly but that it doesn’t do anything other than changing from follow to following. If this is a “UI” push then I believe it should fill the UI requirements and if it is a “functionality” push it should add the functionality of the button meaning that it starts following the itinerary. I am not saying that what you did is useless simply that it is unfinished and doesn’t add any value to the project in its current state and therefore shouldn’t be pushed into main,

2024-05-15 09:19 UTC, imaneb942 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
> +        topBar = {
thank you @ethangraham2001 I'll try to implement this change asap

2024-05-15 12:02 UTC, gunnm0 approved these changes
nice job, this looks nice and will be a good base to work on for MS4

2024-05-15 12:02 UTC, gunnm0 commented on app/src/test/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreenKtTest.kt
> +
test are a little empty, however I think it is better to work on the apps functionnality for now and add tests later.

2024-05-15 13:42 UTC, ethangraham2001 approved these changes

2024-05-15 13:42 UTC, merged