Refactored ItineraryBuilder, connected UI of the tags part of the itinerary creation process
WanderWise-Inc/app pull request #228
Opened 2024-05-15 12:50 UTC by YofiY

- refactored ItineraryBuilder:	
        - renamed `visible` attribute to `isPublic`
	- changed `time`'s type from `Int` to `Float`

- Connected the UI to the backend inside of `CreationStepChooseTags.kt`

2024-05-15 14:04 UTC, ethangraham2001 reviewed
Looks good but there are a couple additional considerations

- the offline storage stack needs to be modified, notably the protobuf files and serializers
- The firestore data that we have currently will need to be modified

This introduces more work that someone is going to have to do, albeit not a huge amount. Nonetheless, we should probably discuss during the next standup meeting.

2024-05-15 14:04 UTC, ethangraham2001 commented on app/src/main/java/com/github/wanderwise_inc/app/DemoSetup.kt
> +          isPublic = true,
name is clearer

2024-05-15 14:04 UTC, ethangraham2001 commented on app/src/main/java/com/github/wanderwise_inc/app/DemoSetup.kt
> +          time = 3f,
Time was initially a float before, but we changed it to an integer as we felt that it was overkill to have values like "1.3" hours.
We can change it, but I think we should chat and see if we agree on the extra precision

2024-05-16 11:00 UTC, gunnm0 requested changes
There are a few issues I see with this code, firstly if we change to the next screen since you don't compose the values of CreateItineraryViewModel.newItineraryBuilder, nothing gets composed and you can't see the value that were previously written. Also you should at least reach 80% test coverage before the code is pushed into main.

2024-05-17 07:52 UTC, gunnm0 requested changes
there are issues with this code as well as missing tests.

2024-05-17 07:52 UTC, gunnm0 commented on app/src/main/java/com/github/wanderwise_inc/app/viewmodel/CreateItineraryViewModel.kt
> +    imageRepository.uploadImageToStorage("profilePicture/${userUid}")
First of all, why is the itineraryBannerPicture saved at the path profilePicture/${userUid}, this task is more tricky than this, we need to push the image with the itinerary uid which you can only get once the intinerary has been pushed to firebase.

2024-05-18 19:57 UTC, closed without merging