Fixed ProfilePicture issue and added logic to correctly delete an Itinerary, and modified the ImageRepositoryLogic
WanderWise-Inc/app pull request #263
Opened 2024-05-18 10:42 UTC by engjellismaili

### Profile Picture

> Fixed the issue with the `ProfilePicture`. Now, we are using `Coil` to display images.

### ImageRepository

> Previously, the `fetchImage` function returned a `Flow<Bitmap>`, now we get directly the URL of the image and return a `Uri`. 
> With this new implementation, there isn't a limit of what we can fetch from `Storage`
> Had to reimplement the tests to fit the new implementation

### Itinerary Deletion

> Added a button to the `PreviewItineraryScreen` (thought this could be a good place to add a delete button but can be changed). 
> This button now deletes the `Itinerary` from `Firestore`, and delete every reference to it in the `Users` liked list.

2024-05-18 11:41 UTC, ThomasPFMuller approved these changes
Everything lgtm, there might be a variable that you abandoned but did not remove, please check if that is the case.

2024-05-18 11:41 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/data/ImageRepositoryImpl.kt
lgtm

2024-05-18 11:41 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/data/ItineraryRepositoryImpl.kt
lgtm

2024-05-18 11:41 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/model/location/Itinerary.kt
> +    val likedUsers: MutableList<String> = mutableListOf()
So now that we have added a list of users that have liked the itinerary as attribute do we still need the numLikes attribute? Since it can be directly calculated as the size of the list of users

2024-05-18 11:41 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
So if I understand correctly, the profile picture updates instantaneously because you increment the ctr variable with makes the composable recompose since it listens to a remember(_, ctr) ?

2024-05-18 11:41 UTC, ThomasPFMuller commented on app/src/test/java/com/github/wanderwise_inc/app/data/ImageRepositoryTest.kt
>    @Mock private lateinit var taskByteArray: Task<ByteArray>
is the mocked variable taskByteArray still used? If not you should remove it

2024-05-18 11:41 UTC, ThomasPFMuller commented on app/src/test/java/com/github/wanderwise_inc/app/data/ItineraryRepositoryTest.kt
lgtm

2024-05-18 11:43 UTC, ThomasPFMuller approved these changes
Good idea to make delete button in the same style as an error to warn the user. If motivated we can later create a pop up that asks the user to confirm they indeed want to delete the itinerary

2024-05-18 12:14 UTC, ethangraham2001 requested changes
The profile picture updated was much needed, and is well implemented. Has my approval

Imo the updates related to deleting itineraries adds too much unnecessary complexity, and there are some implementation choices that should be refactored (for example passing a viewmodel as argument into a viewmodel method).

I think should be split into two separate PRs

2024-05-18 12:14 UTC, ethangraham2001 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfilePicture.kt
lgtm. I check it out on the emulator and the image display is definitely improved.

2024-05-18 12:14 UTC, ethangraham2001 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> +                  imageRepository.setCurrentFile(null)
Direct interaction between the repository and the UI isn't recommended. Could this go through `profileViewModel` instead?

2024-05-18 12:14 UTC, ethangraham2001 commented on app/src/main/java/com/github/wanderwise_inc/app/data/ItineraryRepositoryImpl.kt
> +                  Log.w("ProfileRepositoryImpl", exception)
Wrong log tag

2024-05-18 12:14 UTC, ethangraham2001 commented on app/src/main/java/com/github/wanderwise_inc/app/data/ItineraryRepositoryImpl.kt
> +          throw it
Throwing an error that should be handled by viewmodel, but isn't. Will likely crash the app if the `userUid` isn't present in the Itinerary's "likedUsers" list.

2024-05-18 12:14 UTC, ethangraham2001 commented on app/src/main/java/com/github/wanderwise_inc/app/viewmodel/ItineraryViewModel.kt
> +      profileViewModel: ProfileViewModel,
We shouldn't be passing a viewmodel as argument into another viewmodel. We should be separating concerns between different data interactions instead of coupling them together too tightly.

Moreover, as I expressed before, I don't think it is optimal for us to be storing users who have liked an itinerary alongside it. It would be beneficial to keep state of users that have liked an itinerary in a more elaborate product, but I will explain why I don't think that this should be the case for our POC.

- We don't give users access to who has liked their itinerary; we only use it for deletion (cleaning up no-long-existing itineraries from `Profile` models)
- What happens if a profile is deleted, and we delete an itinerary?
- We have to do more book-keeping for deletion, when in reality it should just be a case of removing it from storage.

I will contrast with how I personally think this should be handled:

- on liking an itinerary, we add the UID to the profile's liked-itineraries list (as we are doing)
- on deletion, we just delete the itinerary from storage and leave the profile untouched (this "wastes" a few bytes worth of storage)
- When the profile tries to access an itinerary in its liked-itineraries list that no longer exists, it just won't show up. At this point, we can remove it from that profile's liked itineraries list (this is yet to be implemented). Alternatively, we don't even need to remove it from the profile's liked itineraries list, it's only a few wasted bytes in storage which isn't our concern for a POC.

2024-05-18 12:14 UTC, ethangraham2001 commented on app/src/main/java/com/github/wanderwise_inc/app/viewmodel/ProfileViewModel.kt
lgtm

2024-05-18 16:16 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/DemoSetup.kt
>            title = "Shopping then adventure",
Yes, gonna do it

2024-05-18 16:17 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/model/location/Itinerary.kt
> +    val likedUsers: MutableList<String> = mutableListOf()
This was the whole point of my implementation

2024-05-18 16:18 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
> +                    NavigationActions(navController).navigateTo(TOP_LEVEL_DESTINATIONS[4])
Yes, just wanted to add some navigations after the actions of the button, but didn't really knew how to properly do it

2024-05-18 16:18 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
> +                  imageRepository.setCurrentFile(null)
I can check but here since we only upload some images, i thought that calling directly the imageRepository could be quicker

2024-05-18 16:19 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/data/ItineraryRepositoryImpl.kt
> +                  Log.w("ProfileRepositoryImpl", exception)
My bad, gonna change it

2024-05-18 16:21 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/viewmodel/ItineraryViewModel.kt
> +      profileViewModel: ProfileViewModel,
Ok i see your pov. While trying to add the delete logic for an itinerary, i thought that remove it from users likedItineraries would be cleaner. However, if you think that this isn't required in our app then i will remove it.

2024-05-18 16:24 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/model/location/Itinerary.kt
> +    val likedUsers: MutableList<String> = mutableListOf()
This will be removed after discussion with @ethangraham2001

2024-05-18 16:26 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
Yes exactly. Since we added a logic to not constantly call the fetchImage function, we had to find a way to "trigger" the call to the fetchImage. I also had to change the implementation of uploadImageToStorage since the counter was incremented before the call of the function finished.

2024-05-18 16:26 UTC, engjellismaili commented on app/src/test/java/com/github/wanderwise_inc/app/data/ImageRepositoryTest.kt
>    @Mock private lateinit var taskByteArray: Task<ByteArray>
Nop, thanks for the catch, will remove it.

2024-05-18 20:09 UTC, ThomasPFMuller requested changes
I have a few questions before I re-approve the changes

2024-05-18 20:09 UTC, ThomasPFMuller commented on app/src/test/java/com/github/wanderwise_inc/app/viewmodel/ItineraryViewModelTest.kt
> +    val emittedItineraryList = itineraryViewModel.getUserItineraries("DEFAULT_USER_UID").first()
Why did you change this to a string?

2024-05-18 20:09 UTC, ThomasPFMuller commented on app/src/test/java/com/github/wanderwise_inc/app/data/ItineraryRepositoryTest.kt
> -  @Test
Why did you remove all these tests?

2024-05-18 20:09 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
> +                  NavigationActions(navController).navigateTo(TOP_LEVEL_DESTINATIONS[4])
Here I suggest you user TopLevelDestination.Profile instead of TOP_LEVEL_DESTINATIONS[4]

2024-05-18 20:09 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
> +                    .verticalScroll(scrollState),
What are you using this modifier for? Is it to allow the banner to be dragged up and down?

2024-05-18 20:10 UTC, engjellismaili commented on app/src/test/java/com/github/wanderwise_inc/app/viewmodel/ItineraryViewModelTest.kt
> +    val emittedItineraryList = itineraryViewModel.getUserItineraries("DEFAULT_USER_UID").first()
I hadn't the DEFAULT_USER_UID parameter anymore. I think that i removed one useless file that declared it

2024-05-18 20:12 UTC, engjellismaili commented on app/src/test/java/com/github/wanderwise_inc/app/data/ItineraryRepositoryTest.kt
> -  @Test
After discussion with @ethangraham2001 , we came to the point that it won't be necessary to add some logic to delete the Itinerary for each user. So, i removed the function i made (to avoid having commented code / useless code) and removed the tests as well. The code is saved within the commits, so it's easy to refind it and add it again if we need.

2024-05-18 20:12 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
> +                  NavigationActions(navController).navigateTo(TOP_LEVEL_DESTINATIONS[4])
Thanks i will change that

2024-05-18 20:13 UTC, engjellismaili commented on app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
> +                    .verticalScroll(scrollState),
I think that's what @ethangraham2001 added, but i think that there was an issue with the ItineraryBanner. If the description was too long, the Button didn't get displayed correctly. So he made that change to be able to see it.

2024-05-18 20:22 UTC, ThomasPFMuller approved these changes
Nice, if you really want to be perfect you can import Destinations.TopLevelDestinations so that the preceeding Destinations. can be removed this is me getting picky

2024-05-19 09:45 UTC, ethangraham2001 approved these changes
Everything is looking good to me. Thanks for addressing requested changes.

2024-05-19 09:49 UTC, merged

2024-05-19 09:50 UTC, ethangraham2001 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
> +                    .verticalScroll(scrollState),
Yeah when there was too much text, we couldn't see the delete button. To fix this, made the primary column scrollable thus allowing everything to be displayed - even with very long titles / descriptions.