Test/e2e create itinerary
WanderWise-Inc/app pull request #282
Opened 2024-05-19 21:23 UTC by ThomasPFMuller

Created E2E test for itinerary creation logic
1. Login
2. Navigate to creation screen
3. Start creating an itinerary
4. Begin by tracking the user for 5 seconds to obtain 1-2 markers placed by tracking
5. Assert the markers were added
6. Switch to manual location add
7. Add a new Location
8. Search for GooglePlex
9. Add the first result
10. Assert marker was added
11. Navigate to Title/Description screen
12. Input a title and a description
13. navigate to Tags screen
14. Input a price, time and tag
15. Navigate to Preview Banner and then Preview Itinerary screen
16. Finish creating itinerary
17. Assert navigated to Profile and Itinerary present among user's itineraries

2024-05-19 21:44 UTC, 276746 requested changes
This is a good test but it might need just some small modifications to avoid weird futur behavior

2024-05-19 21:44 UTC, 276746 commented on app/src/main/java/com/github/wanderwise_inc/app/ui/TestTags.kt
Really sastifying to see an organized file !

2024-05-19 21:44 UTC, 276746 commented on app/src/androidTest/java/com/github/wanderwise_inc/app/e2e/CreateItineraryE2ETest.kt
> +        composeTestRule.waitUntil(5000L) { true } // track for 5 seconds
This is the opposite, if you want to wait for 5sec you need to pass `false` since `waitUntil` will wait until the lambda is `true` or until it times out and I think it will throw an `TimeoutException` meaning that you cant really use it to wait an arbitrary long amout of time this way. (I fell into this trap too)

2024-05-19 21:44 UTC, 276746 commented on app/src/androidTest/java/com/github/wanderwise_inc/app/e2e/CreateItineraryE2ETest.kt
> +        composeTestRule.onNodeWithTag("${TestTags.CREATE_ITINERARY_LOCATION}_Placed marker").assertExists()
If you want to find a subTestTag you can use the funtion in `E2EUtils` called `hasSubTestTag(subTestTag: String): SemanticsMatcher` you can then try to find a specific node by using either `filter` or `onAllNodes` like this: 
```
composeTestRule.onAllNodes(E2EUtils.hasSubTestTag(TestTags.CREATE_ITINERARY_LOCATION)).first()
```
were this return the all the nodes having the sub string of the `subTestTag` in their `TestTag` and then taking the first one

2024-05-19 21:59 UTC, ThomasPFMuller commented on app/src/androidTest/java/com/github/wanderwise_inc/app/e2e/CreateItineraryE2ETest.kt
> +        composeTestRule.waitUntil(5000L) { true } // track for 5 seconds
Done, thank you

2024-05-19 22:39 UTC, ThomasPFMuller commented
Want to add flow for the following feature: clicking on map to add waypoint

2024-05-23 11:06 UTC, 276746 approved these changes
Well done !

2024-05-23 12:06 UTC, merged

2024-05-23 12:07 UTC, ThomasPFMuller commented
Solves issue #290