Follow itinerary using google maps
WanderWise-Inc/app pull request #286
Opened 2024-05-22 11:09 UTC by YofiY

Worked on launching google maps with the itinerary to follow when clicking on the "follow" button.
It is launching an intent with a google specified URI. Manually it seems to work fine.

2024-05-23 12:50 UTC, ThomasPFMuller requested changes
Could you write some basic tests just to verify that the FollowItineraryOnGoogleMaps function is indeed being called. For example you can simulate a click, mock the itineraryViewModel, so that the call increments a variable which you then assert == 1. Also you should be able to test the functions in the VM seperately, verifying that the intent is correctly resolved

2024-05-23 12:50 UTC, ThomasPFMuller commented on app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
> +  val context = LocalContext.current
Isn't there a way of getting the context from the appModule? This would centralize the call.

2024-05-23 22:11 UTC, YofiY commented on app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
> +  val context = LocalContext.current
passing the app module would be cumbersome and require some refactoring, moreover I believe that this is much more readable.

2024-05-24 07:40 UTC, 276746 approved these changes

2024-05-24 07:55 UTC, ThomasPFMuller approved these changes
LGTM

2024-05-24 07:56 UTC, merged