Updates to tinerary backend
WanderWise-Inc/app pull request #60
Opened 2024-04-09 14:02 UTC by ethangraham2001

Added preference-based filtering of itineraries
- `Tag` type (`String`) that represents an itinerary tag, with an `object` containing common instances
- updated `Itinerary` with a list of tags, as well as upvotes / downvotes. Added a scoring method that scores an itinerary based on preferences, as well as overall rating
- implemented preference-based filtering, and sorting based on scoring in `MapViewModel`
- Added a function for computing distance between two `Location`s (goal is to use for sorting in the future)
- Added some no-argument constructors which are needed by firebase
- did some general refactoring for prettier code uwu

2024-04-09 14:45 UTC, ThomasPFMuller requested changes
Ambiguities:
- Upvotes/downvotes not yet implemented?

Problems:
- fun scoreFromPreferences in Itinerary can have division by zero if there are no upvotes or downvotes -> multiplication by infinity

2024-04-09 14:54 UTC, YofiY reviewed
- The logic implemented for the sorting of itinerary by preferences lgtm 
- The mapViewModel follows want is needed in order to sort
- The itinerary may need additional attributes  structure modified in order to order to fit in the descriptions in the itinerary preivew banner better but it looks good for now as this is a futur task

2024-04-09 14:54 UTC, YofiY commented on app/src/main/java/com/github/wanderwise_inc/app/MainActivity.kt
lgtm

2024-04-09 14:54 UTC, YofiY commented on app/src/main/java/com/github/wanderwise_inc/app/model/location/Itinerary.kt
> +            if (tags.size >= 3)
may want to use the constant MAX_TAGS

2024-04-09 14:54 UTC, YofiY commented on app/src/main/java/com/github/wanderwise_inc/app/model/location/Location.kt
> +
the math seems correct !

2024-04-09 14:54 UTC, YofiY commented on app/src/main/java/com/github/wanderwise_inc/app/model/location/Tag.kt
> +object ItineraryTags {
We will have to discuss further the exact tags but now for the logic, it looks good to me

2024-04-09 14:54 UTC, YofiY commented on app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
> +            Text(
from the last meeting we want the itinerary to show the display the following :
- La liste des points wander stops
	- Description pour chaque stop 
	- Photos
- Cout
- Temps
- Rating
- Profile du créateur 
- Tags
We can discuss this further during our next standup meeting

2024-04-09 14:54 UTC, YofiY commented on app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
> +            Text(
I think that these should be attributes of the Itinerary object

2024-04-09 14:54 UTC, YofiY commented on app/src/main/java/com/github/wanderwise_inc/app/viewmodel/MapViewModel.kt
> +    fun getItinerariesFromPreferences(preferences: ItineraryPreferences): Flow<List<Itinerary>>{
lgtm ! good stuff

2024-04-10 11:22 UTC, ThomasPFMuller approved these changes
good stuff, nice changes

2024-04-10 11:23 UTC, merged