Map/user position
WanderWise-Inc/app pull request #78
Opened 2024-04-11 11:34 UTC by 276746

Client and helper function to get the position of the user

2024-04-11 12:27 UTC, imaneb942 commented on app/src/main/java/com/github/wanderwise_inc/app/viewmodel/ContextExt.kt
Line 13 and line 20, what is the difference between the two functions?

2024-04-11 12:30 UTC, imaneb942 commented on app/src/main/java/com/github/wanderwise_inc/app/viewmodel/UserLocationClient.kt
the overall class is good and well implemented, think of writing some comments for futur reads

2024-04-11 12:33 UTC, 276746 commented on app/src/main/java/com/github/wanderwise_inc/app/viewmodel/LocationService.kt
It will be used to track the user on the MapScreen

2024-04-11 12:33 UTC, 276746 commented on app/src/main/java/com/github/wanderwise_inc/app/viewmodel/UserLocationClient.kt
Will add

2024-04-11 12:34 UTC, imaneb942 reviewed
Your implementations are nice overall, the main thing for me is a lack of commentary but otherwise read my comments and you'll find the few quetions I had.

2024-04-11 12:35 UTC, 276746 commented on app/src/main/java/com/github/wanderwise_inc/app/viewmodel/ContextExt.kt
One for Coarse permission the other for Fine permission

2024-04-11 16:15 UTC, imaneb942 approved these changes
The changes are approved, and are ready to be merged to the main, thank you for answering my questions

2024-04-11 16:17 UTC, imaneb942 requested changes
There are conflits in your buildGradle and your Login Screen, I will share those conflicts with you, please resolve them

2024-04-11 19:14 UTC, saraanej reviewed
Clean code, good job ! Good practices were used. I had some quick questions about implementation but everything looks good so far. 
Try to write tests for your UI and logic as you go to make it easier for you to have a good test coverage

2024-04-11 19:14 UTC, saraanej commented on app/src/main/java/com/github/wanderwise_inc/app/viewmodel/UserLocationClient.kt
> +    @SuppressLint("MissingPermission")
Why is this line necessary for this part of code ?

2024-04-11 19:14 UTC, saraanej commented on app/src/main/java/com/github/wanderwise_inc/app/viewmodel/LocationClient.kt
> +interface LocationClient {
Very good practice to use an interface as it allows you flexibility and modularity !

2024-04-11 19:14 UTC, saraanej commented on app/src/main/java/com/github/wanderwise_inc/app/viewmodel/UserLocationClient.kt
> +                throw LocationClient.LocationException("No mean of tracking position")
Good practice to give explicit messages when an error happens

2024-04-11 19:14 UTC, saraanej commented on app/src/main/java/com/github/wanderwise_inc/app/viewmodel/LocationClient.kt
> +    fun getLocationUpdates(interval: Long): Flow<Location>
A remark for future tests and implementations, don't forget to prevent negative or zero values from being passed, which can lead to unexpected behavior or errors

2024-04-11 20:04 UTC, 276746 commented on app/src/main/java/com/github/wanderwise_inc/app/viewmodel/UserLocationClient.kt
> +    @SuppressLint("MissingPermission")
Because for the lines 62-66, we need to check if the permissions have been given which we did check at line 40 with the function hasLocationPermission() but the compiler still wants an explicit permission check. We could just implement hasLocationPermission() before the problematic lines to resolve this issue but I may need this function and this would be redundant. Again I am not sure if I will ever need to check those specific permissions, but if I need some another permissions check for others permission I would implement it in ContextExt so all functions checking permissions are centralized in this file.
lines 62-66 for reference:
```kotlin
client.requestLocationUpdates(
                request,
                locationCallback,
                Looper.getMainLooper()
            )
```

2024-04-12 08:38 UTC, imaneb942 approved these changes
I will merge the changes great additions and thank you for your reactivity

2024-04-12 08:38 UTC, merged

2024-04-12 08:41 UTC, 276746 commented
Delete after merge